// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaGaAepZFFZDY--JrB8Uo1NNeCXyDzr0Y',
    appId: '1:148562372363:android:9b117ec85ce7922982e40e',
    messagingSenderId: '148562372363',
    projectId: 'besty-172a5',
    storageBucket: 'besty-172a5.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCO5UaBBkFOGTeGDPNDf4GZ0uyMpZYmNE',
    appId: '1:148562372363:web:75d75bbdf49bf54d82e40e',
    messagingSenderId: '148562372363',
    projectId: 'besty-172a5',
    authDomain: 'besty-172a5.firebaseapp.com',
    storageBucket: 'besty-172a5.firebasestorage.app',
    measurementId: 'G-WWJMDL1LT2',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLDuEFR7_2WVB3z1s5JrDgM2RUAWbT9mw',
    appId: '1:148562372363:ios:25b53bf5323125e882e40e',
    messagingSenderId: '148562372363',
    projectId: 'besty-172a5',
    storageBucket: 'besty-172a5.firebasestorage.app',
    iosBundleId: 'com.example.betsy',
  );

}